search01:
  image: lordhackalot/aws-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  privileged: true
  environment:
    - "constraint:node==swarm-ec2-master" 
    - ELASTICNODE=aws-search01
    - INST_ADDR=172.24.4.196
    - INST_ADDR01=172.24.4.196
    - INST_ADDR02=172.24.4.217
    - INST_ADDR03=172.24.4.199
    
search02:
  image: lordhackalot/aws-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  privileged: true
  environment:
    - "constraint:node==swarm-ec2-node-00" 
    - ELASTICNODE=aws-search02
    - INST_ADDR=172.24.4.217
    - INST_ADDR01=172.24.4.196
    - INST_ADDR02=172.24.4.217
    - INST_ADDR03=172.24.4.199
    
search03:
  image: lordhackalot/aws-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  privileged: true
  environment:
    - "constraint:node==swarm-ec2-node-01" 
    - ELASTICNODE=aws-search03
    - INST_ADDR=172.24.4.199
    - INST_ADDR01=172.24.4.196
    - INST_ADDR02=172.24.4.217
    - INST_ADDR03=172.24.4.199
 
