search01:
  image: lordhackalot/aws-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  privileged: true
  environment:
    - "constraint:node==swarm-ec2-master" 
    - ELASTICNODE=aws-search01
    
search02:
  image: lordhackalot/aws-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  privileged: true
  environment:
    - "constraint:node==swarm-ec2-node-00" 
    - ELASTICNODE=aws-search02
    
search03:
  image: lordhackalot/aws-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  privileged: true
  environment:
    - "constraint:node==swarm-ec2-node-01" 
    - ELASTICNODE=aws-search03
